project:
  type: website
  output-dir: _site

website:
  title: "Florin Cojocariu"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: ["custom.css"]
    reference-location: margin
    cap-location: margin
  pdf:
    documentclass: article