project:
  type: website
  output-dir: _site

website:
  title: "Florin Cojocariu"
  site-url: "https://florin.antimaterie.ro"
  format:
  html:
    css: ["styles.css"]
    self-contained: true
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    toc-location: left
    reference-location: margin
  pdf:
    documentclass: article
