project:
  type: website
  output-dir: _site
website:
  title: "Florin Cojocariu"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:                          # ← Add this website-level sidebar
    style: "floating"
    search: false
    contents: auto                  # ← This will auto-generate from your content
  comments:
    giscus:
      repo: aathanor/Philosophy
      repo-id: "R_kgDOOvbpNQ"
      category: "General"
      category-id: "DIC_kwDOOvbpNc4CqifF"
      mapping: "pathname"
      reactions-enabled: true
      input-position: "bottom"
      theme: "light"
      language: "en"
format:
  html:
    theme: cosmo
    css: ["custom.css"]
    reference-location: margin
    cap-location: margin
    toc: true                    # ← New
  pdf:
    documentclass: article