project:
  type: website
  output-dir: _site

website:
  title: "Florin Cojocariu"
  navbar:
    left:
      - href: index.qmd
        text: Home
  comments:
    giscus:
      repo: your-username/your-repo-name
      repo-id: "R_kgDOOvbpNQ"
      category: "General"
      category-id: "DIC_kwDOOvbpNc4CqifF"
      mapping: "pathname"
      reactions-enabled: true
      input-position: "bottom"
      theme: "light"
      language: "en"

format:
  html:
    theme: cosmo
    css: ["custom.css"]
    reference-location: margin
    cap-location: margin
  pdf:
    documentclass: article