---
author: Florin Cojocariu
date: 01.18.2025
title: How Analytic Philosophy got into a straight jacket - Extended Abstract
---


> *The traditional misunderstanding of human being starts with Plato's fascination with theory.* (Dreyfus 2006)

Contemporary analytic philosophy[^1] sees papers like bricks in a vast edifice of knowledge, each with its clearly defined shape and purpose, each fitting precisely with its neighbors. While this approach has undeniable value --- indeed, we need specific bricks fitting with each other --- we must ask whether bricks alone can build the cathedral of understanding we seek. Perhaps we also require sketches of the whole, experimental scaffolding, seemingly imperfect materials that might prove crucial to the larger structure, or even tear down a perfectly good-looking wall which proves to create a dead end for a promising corridor. But there is also in this metaphor a more profound question regarding the relation between knowledge and understanding: having innumerable small truths, with valid proofs, do not necessarily bring us closer to understanding and wisdom, the original reason for philosophy[^2]. Something may be missing. This essay is an attempt to take a historical look at how the criteria of a \`\`well-written philosophy paper'' evolved since the birth of Analytic Philosophy around the 1900s, how they evolved into today's straight jacket and why the mold they became, imprinted into the structure of almost every paper today, may be a problem. In the end, we'll look at some possible alternatives.

### The Problem

A glance at any major philosophy journal's submission guidelines reveals this 'analytical' imperative: papers must state their thesis clearly, structure arguments logically, and proceed systematically toward their conclusion. ("Writing and Publishing in Philosophy" 2024).

Yet, some of philosophy's most influential works resist this format. Consider Wittgenstein's Philosophical Investigations[^3] --- if its insight could be reduced to "language is usage," it would hardly require its complex form; the Tractatus is escaping even more any attempt to fit its "picture theory of language" into some "main claim/demonstration" template. Or examine Heidegger's Being and Time[^4], which despite (or perhaps through) its notorious difficulty, transformed 20th-century philosophy without conforming to what we now consider proper philosophical argumentation. Even Plato's dialogues, foundational to Western philosophy, often end in aporia rather than clear conclusions.

This raises a valid question: has the "main claim/argument/proof" requirement become too restrictive for what we call (analytical) philosophical inquiry?[^5]

### The State of The Art

While it appears there is no established group of philosophers actively writing on the influence of publishing criteria on the philosophical inquiry today --- the difficult existence of such a group, basically challenging all of major philosophy publishers' orientation, should be recognized --- a broader critique of "analytical method" can be found in a series of books and researches during the past decades; some heavy weights like (Feyerabend 1993) and (Rorty 1980) questioned the analytical method per se; there are also more recent (and somewhat disputed) works looking at the specific problems of the analytical philosophy like (Unger 2014); then there is the exhaustive and well regarded historical take of (Glock 2008). More specifically, we'll use the work of (Katzav 2018) who documented in depth the takeover of major philosophy journals by analytical philosophers during the 1960s and the way this "coup" contributed to the situation today. However, on the narrow "straight jacket structure imposed by main philosophical journals", the nature of the subject make it so that there is no proper "state of the art".

### The Roadmap

Our investigation proceeds in four parts. **First**, we examine the historical emergence of the \`\`main claim/proof'' paradigm and its relationship to analytical philosophy, but also recent research about how the form may impose undue restrictions on philosophical thinking. We will use some of the critique Rorty and Feyerabend brought to the quasi-scientific method of analytical philosophy. We'll rely on "The Uses of Argument" (Toulmin 2003) for the historical look **Second**, we'll investigate how the criteria imposed by major journals for the structure of the arguments all but excluded non-analytical papers from publication leveling the field in favor of the Analytic Philosophy, relying mostly on (Katzav 2018) research. **Third**, we'll consider some unusual remarkable outliers[^6] to argue about how this straight jacket may diminish the philosophical discourse, particularly in an era of increasing academic specialization and a very specific need for interdisciplinarity. And **finally**, we look at some alternative formats as a starting point for further research.

(originally prepared for Academic Writing Class)

## Bibliography:

(only for works quoted in this chapter)

::::::::::::::::: {#refs .references .csl-bib-body .hanging-indent entry-spacing="0"}
::: {#ref-baierTrustAntitrust1986 .csl-entry}
Baier, Annette. 1986. "Trust and Antitrust." *Ethics* 96 (2). University of Chicago Press: 231--60. doi:[10.1086/292745](https://doi.org/10.1086/292745).
:::

::: {#ref-davidsonVeryIdeaConceptual1973 .csl-entry}
Davidson, Donald. 1973. "On the Very Idea of a Conceptual Scheme." *Proceedings and Addresses of the American Philosophical Association* 47. American Philosophical Association: 5--20. doi:[10.2307/3129898](https://doi.org/10.2307/3129898).
:::

::: {#ref-dreyfusBeingintheworldCommentaryHeideggers2006 .csl-entry}
Dreyfus, Hubert L. 2006. *Being-in-the-World: A Commentary on Heidegger's Being and Time, Division i*. 13. \[print.\]. Cambridge, Mass.: MIT Press.
:::

::: {#ref-feyerabendMethod1993 .csl-entry}
Feyerabend, Paul. 1993. *Against Method*. 3rd ed. London ; New York: Verso.
:::

::: {#ref-gettierJustifiedTrueBelief1963 .csl-entry}
Gettier, Edmund L. 1963. "Is Justified True Belief Knowledge?" *Analysis* 23 (6). \[Analysis Committee, Oxford University Press\]: 121--23. doi:[10.2307/3326922](https://doi.org/10.2307/3326922).
:::

::: {#ref-glockWHATANALYTICPHILOSOPHY2008 .csl-entry}
Glock, Hans-Johann. 2008. *WHAT IS ANALYTIC PHILOSOPHY?* Cambridge University Press. doi:[10.1017/cbo9780511841125](https://doi.org/10.1017/cbo9780511841125).
:::

::: {#ref-katzavAnalyticPhilosophy1925692018 .csl-entry}
Katzav, Joel. 2018. "Analytic Philosophy, 1925--69: Emergence, Management and Nature." *British Journal for the History of Philosophy* 26 (6): 1197--1221. doi:[10.1080/09608788.2018.1450219](https://doi.org/10.1080/09608788.2018.1450219).
:::

::: {#ref-martinichPhilosophyLanguage1996 .csl-entry}
Martinich, Aloysius, ed. 1996. *The Philosophy of Language*. 3. ed. New York Oxford: Oxford University Press.
:::

::: {#ref-maslowPsychologyScience1962 .csl-entry}
Maslow, Abraham H. 1962. *Psychology of Science*. Place of publication not identified: Harper & Row. doi:[10.1037/10793-000](https://doi.org/10.1037/10793-000).
:::

::: {#ref-nagelWhatItBe1974 .csl-entry}
Nagel, Thomas. 1974. "What Is It Like to Be a Bat?" *The Philosophical Review* 83 (4). \[Duke University Press, Philosophical Review\]: 435--50. doi:[10.2307/2183914](https://doi.org/10.2307/2183914).
:::

::: {#ref-rortyPhilosophyMirrorNature1980 .csl-entry}
Rorty, Richard. 1980. *Philosophy and the Mirror of Nature*. 2nd print., with corrections. Princeton Paperbacks Philosophy. Princeton, NJ: Princeton Univ. Press.
:::

::: {#ref-toulminUsesArgumentUpdated2003 .csl-entry}
Toulmin, Stephen E. 2003. *The Uses of Argument, Updated Edition*.
:::

::: {#ref-ungerEmptyIdeasCritique2014 .csl-entry}
Unger, Peter K. 2014. *Empty Ideas: A Critique of Analytic Philosophy*. New York, NY: Oxford University Press.
:::

::: {#ref-WritingPublishingPhilosophy .csl-entry}
"Writing and Publishing in Philosophy." 2024. *British Philosophical Association*. Accessed December 10.
:::
:::::::::::::::::

[^1]: While a clear definition of what is today "analytic philosophy" may be disputable, there is still an "analytic style" in philosophical argumentation, very close to scientific argumentation, pervasive in the majority of the writings in the "non-continental" philosophy. The scope of this text is limited to what we understand today by "analytic philosophy" with a potential focus on its specific domain, the philosophy of language.

[^2]: This is actually one of the main criticism under which traditional AP all but collapsed; only that its method continues to haunt us, like a ghost.

[^3]: In Saul Kripke's words: "Rather the Investigations is written as a perpetual dialectic, where persisting worries, expressed by the voice of the imaginary interlocutor, are never definitively silenced." (Martinich 1996, 37)

[^4]: We can't simply compare books to papers, but philosophy books had a role not fulfilled today by any kind of canon in academic philosophy papers.

[^5]: It must be noted this goes beyond policy debates as ours may be a case where form drives function, reminding of Maslow's observation "it is tempting, if the only tool you have is a hammer, to treat everything as if it were a nail." (Maslow 1962)

[^6]: We'll consider 4 influential papers who breaked "the mold" in different ways: ("Is Justified True Belief Knowledge?" Gettier 1963), ("On the Very Idea of a Conceptual Scheme" Davidson 1973), ("What Is It Like to Be a Bat?" Nagel 1974), ("Trust and Antitrust" Baier 1986)
