name: Render and Deploy
on:
  push:
    branches: [main]
    paths:
      - '**.qmd'
      - '**.md' 
      - 'essays/**'
      - 'papers/**'
      - 'presentations/**'
      - 'index.qmd'
      - '_quarto.yml'
      - 'custom.css'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Install TinyTeX
        run: quarto install tinytex
      
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
      
      - name: Debug - List files
        run: |
          echo "Root directory:"
          ls -la
          echo "_site directory:"
          ls -la _site/ || echo "_site does not exist"
      
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: philosophy
          directory: _site